export const BASE_ROUTE="/";
export const REGISTRATION_ROUTE="/register-student";
export const STUDENTS_LIST_ROUTE="/students-list";
export const STUDENT_EDIT_ROUTE ='/edit-student/:id'
export const STUDENT_HOME_ROUTE="/home"
export const ATTENDANCE_LIST_ROUTE = '/attendance';
export const ATTENDANCE_LIST_BY_DATE_ROUTE='/attendance-by-date'
export const ATTENDANCE_LIST_BY_STUDENT_ROUTE='/attendance-by-student'
export const ABOUT_ROUTE = '/about'
export const CONTACT_ROUTE = '/contact'
export const LOGIN_ROUTE = "/login";
export const SIGNUP_ROUTE ="/sign_up";